services:
  db:
    image: mysql:8.0.35-debian
    container_name: backend-db-dev
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=films
    volumes:
      - ./config/dev/mysql_dump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-api-dev
    volumes:
      - ./app:/var/www/html/app
      - ./config/dev/virtualhosts/films-alberto-despliegue-dev.api.com.conf:/etc/apache2/sites-enabled/films-alberto-despliegue-dev.api.com.conf
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  mysql-data: